version: '3.8'
services:
  api:
    build: .
    ports:
      - "3145:3145"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/eventscanner
      - NODE_ENV=development
      - JWT_SECRET=your-local-secret-key
    volumes:
      - .:/app
      - /app/node_modules
    # Für Hot Reload im Development
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "cluster0.yvxnxgp.mongodb.net:0.0.0.0"
    command: npm run start:dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=eventscanner

volumes:
  mongodb_data: 