export const popularLocationsByCountry: {
  [country: string]: string[];
} = {
  USA: [
    "New York City",
    "Los Angeles",
    "Chicago",
    "Houston",
    "Phoenix",
    "Philadelphia",
    "San Antonio",
    "San Diego",
    "Dallas",
    "San Jose",
    "Austin",
    "Jacksonville",
    "Fort Worth",
    "Columbus",
    "Charlotte",
    "San Francisco",
    "Indianapolis",
    "Seattle",
    "Denver",
    "Washington",
    "Boston",
    "El Paso",
    "Nashville",
    "Detroit",
    "Oklahoma City",
    "Portland",
    "Las Vegas",
    "Memphis",
    "Louisville",
    "Baltimore",
    "Milwaukee",
    "Albuquerque",
    "Tucson",
    "Fresno",
    "Mesa",
    "Sacramento",
    "Atlanta",
    "Kansas City",
    "Colorado Springs",
    "Omaha",
    "Raleigh",
    "Miami",
    "Long Beach",
    "Virginia Beach",
    "Oakland",
    "Minneapolis",
    "Tulsa",
    "Arlington",
    "Tampa",
    "New Orleans",
    "Wichita",
    "Cleveland",
    "Bakersfield",
    "Aurora",
    "Anaheim",
    "Honolulu",
    "Santa Ana",
    "Riverside",
    "Corpus Christi",
    "Lexington",
    "Stockton",
    "Henderson",
    "Saint Paul",
    "St. Louis",
    "Cincinnati",
    "Pittsburgh",
    "Greensboro",
    "Anchorage",
    "Plano",
    "Lincoln",
    "Orlando",
    "Irvine",
    "Newark",
    "Toledo",
    "Durham",
    "Chula Vista",
    "Fort Wayne",
    "Jersey City",
    "St. Petersburg",
    "Laredo",
    "Madison",
    "Chandler",
    "Buffalo",
    "Lubbock",
    "Scottsdale",
    "Reno",
    "Glendale",
    "Gilbert",
    "Winston–Salem",
    "North Las Vegas",
    "Norfolk",
    "Chesapeake",
    "Garland",
    "Irving",
    "Hialeah",
    "Fremont",
    "Boise",
    "Richmond",
    "Baton Rouge",
    "Spokane",
    "Des Moines",
    "Tacoma",
    "San Bernardino",
    "Modesto",
    "Fontana",
    "Santa Clarita",
    "Birmingham",
    "Oxnard",
    "Fayetteville",
    "Moreno Valley",
    "Rochester",
    "Glendale",
    "Huntington Beach",
    "Salt Lake City",
    "Grand Rapids",
    "Amarillo",
    "Yonkers",
    "Aurora",
    "Montgomery",
    "Akron",
    "Little Rock",
    "Huntsville",
    "Augusta",
    "Port St. Lucie",
    "Grand Prairie",
    "Columbus",
    "Tallahassee",
    "Overland Park",
    "Tempe",
    "McKinney",
    "Mobile",
    "Cape Coral",
    "Shreveport",
    "Frisco",
    "Knoxville",
    "Worcester",
    "Brownsville",
    "Vancouver",
    "Fort Lauderdale",
    "Sioux Falls",
    "Ontario",
    "Chattanooga",
    "Providence",
    "Newport News",
    "Rancho Cucamonga",
    "Santa Rosa",
    "Oceanside",
    "Salem",
    "Elk Grove",
    "Garden Grove",
    "Pembroke Pines",
    "Eugene",
    "Cary",
    "Fort Collins",
    "Corona",
    "Springfield",
    "Jackson",
    "Alexandria",
    "Hayward",
    "Lancaster",
    "Lakewood",
    "Clarksville",
    "Palmdale",
    "Salinas",
    "Springfield",
    "Hollywood",
    "Pasadena",
    "Sunnyvale",
    "Macon",
    "Kansas City",
    "Pomona",
    "Escondido",
    "Killeen",
    "Naperville",
    "Joliet",
    "Bellevue",
    "Rockford",
    "Savannah",
    "Paterson",
    "Torrance",
    "Bridgeport",
    "McAllen",
    "Mesquite",
    "Syracuse",
    "Midland",
    "Pasadena",
    "Murfreesboro",
    "Miramar",
    "Dayton",
    "Fullerton",
    "Olathe",
    "Orange",
    "Thornton",
    "Roseville",
    "Denton",
    "Waco",
    "Surprise",
    "Carrollton",
    "West Valley City",
    "Charleston",
    "Warren",
    "Hampton",
    "Gainesville",
    "Visalia",
    "Coral Springs",
    "Columbia",
    "Cedar Rapids",
    "Sterling Heights",
    "New Haven",
    "Stamford",
    "Concord",
    "Kent",
    "Santa Clara",
    "Elizabeth",
    "Round Rock",
    "Thousand Oaks",
    "Lafayette",
    "Athens",
    "Topeka",
    "Simi Valley",
    "Fargo",
    "Norman",
    "Columbia",
    "Abilene",
    "Wilmington",
    "Hartford",
    "Victorville",
    "Pearland",
    "Vallejo",
    "Ann Arbor",
    "Berkeley",
    "Allentown",
    "Richardson",
    "Odessa",
    "Arvada",
    "Cambridge",
    "Sugar Land",
    "Beaumont",
    "Lansing",
    "Evansville",
    "Rochester",
    "Independence",
    "Fairfield",
    "Provo",
    "Clearwater",
    "College Station",
    "West Jordan",
    "Carlsbad",
    "El Monte",
    "Murrieta",
    "Temecula",
    "Springfield",
    "Palm Bay",
    "Costa Mesa",
    "Westminster",
    "North Charleston",
    "Miami Gardens",
    "Manchester",
    "High Point",
    "Downey",
    "Clovis",
    "Pompano Beach",
    "Pueblo",
    "Elgin",
    "Lowell",
    "Antioch",
    "West Palm Beach",
    "Peoria",
    "Everett",
    "Wichita Falls",
    "Green Bay",
    "Daly City",
    "Burbank",
    "Richardson",
    "Pueblo",
    "Gresham",
    "Lewisville",
    "Hillsboro",
    "Ventura",
    "Greeley",
    "Inglewood",
    "Waterbury",
  ],
  France: [
    "Paris",
    "Marseille",
    "Lyon",
    "Toulouse",
    "Nice",
    "Nantes",
    "Montpellier",
    "Strasbourg",
    "Bordeaux",
    "Lille",
    "Rennes",
    "Reims",
    "Le Havre",
    "Saint-Étienne",
    "Toulon",
    "Grenoble",
    "Dijon",
    "Angers",
    "Nîmes",
    "Villeurbanne",
    "Clermont-Ferrand",
    "Le Mans",
    "Aix-en-Provence",
    "Brest",
    "Tours",
    "Amiens",
    "Limoges",
    "Annecy",
    "Perpignan",
    "Boulogne-Billancourt",
    "Metz",
    "Besançon",
    "Orléans",
    "Saint-Denis",
    "Argenteuil",
    "Rouen",
    "Montreuil",
    "Mulhouse",
    "Caen",
    "Nancy",
    "Saint-Paul",
    "Roubaix",
    "Tourcoing",
    "Nanterre",
    "Vitry-sur-Seine",
    "Créteil",
    "Avignon",
    "Poitiers",
    "Dunkerque",
    "Asnières-sur-Seine",
    "Versailles",
    "Courbevoie",
    "Colombes",
    "Fort-de-France",
    "Aulnay-sous-Bois",
    "Saint-Pierre",
    "Rueil-Malmaison",
    "Pau",
    "Aubervilliers",
    "Champigny-sur-Marne",
    "Antibes",
    "Béziers",
    "La Rochelle",
    "Saint-Maur-des-Fossés",
    "Cannes",
    "Calais",
    "Saint-Nazaire",
    "Colmar",
    "Drancy",
    "Ajaccio",
    "Bourges",
    "Issy-les-Moulineaux",
    "Levallois-Perret",
    "Noisy-le-Grand",
    "Quimper",
    "Valence",
    "Villeneuve-d'Ascq",
    "Antony",
    "Troyes",
    "Neuilly-sur-Seine",
    "Sarcelles",
    "Chambéry",
    "Lorient",
    "Pessac",
    "Ivry-sur-Seine",
    "Clichy",
    "Venissieux",
    "Cergy",
    "Saint-Quentin",
    "Niort",
    "Béthune",
    "Cholet",
    "Bondy",
    "La Seyne-sur-Mer",
    "Pantin",
    "Maisons-Alfort",
    "Évry-Courcouronnes",
    "Épinay-sur-Seine",
    "Le Blanc-Mesnil",
    "Fontenay-sous-Bois",
    "Clamart",
    "Fréjus",
    "Villejuif",
    "Chelles",
    "Suresnes",
    "Meaux",
    "Narbonne",
    "Hyères",
    "Saint-Malo",
    "Chalon-sur-Saône",
    "Mantes-la-Jolie",
    "Saint-Brieuc",
    "Bobigny",
    "Carcassonne",
    "Sevran",
    "Charleville-Mézières",
    "Bayonne",
    "Corbeil-Essonnes",
    "Saint-Ouen-sur-Seine",
    "Massy",
    "Vannes",
    "Montrouge",
    "Vaulx-en-Velin",
    "La Roche-sur-Yon",
    "Agen",
    "Beauvais",
    "Brive-la-Gaillarde",
    "Évreux",
    "Saint-Herblain",
    "Saint-Priest",
    "Châteauroux",
    "Roanne",
    "Noisy-le-Sec",
    "Les Abymes",
    "Salon-de-Provence",
    "Châlons-en-Champagne",
    "Albi",
    "Angoulême",
    "Sète",
    "Bastia",
    "Martigues",
    "Caluire-et-Cuire",
    "Tarbes",
    "Compiègne",
    "Melun",
    "Saint-Germain-en-Laye",
    "Garges-lès-Gonesse",
    "Athis-Mons",
    "Mâcon",
    "Choisy-le-Roi",
    "Saint-Martin-d'Hères",
    "Gennevilliers",
    "Saint-André",
    "Le Cannet",
    "Échirolles",
    "Bagneux",
    "Sainte-Geneviève-des-Bois",
    "Saint-Chamond",
    "Livry-Gargan",
    "Anglet",
    "Lens",
    "Thionville",
    "Châtillon",
    "Villepinte",
    "Draguignan",
    "Gagny",
    "Saint-Benoît",
    "Charenton-le-Pont",
    "Rosny-sous-Bois",
    "Saint-Joseph",
    "Nevers",
    "Saint-Laurent-du-Maroni",
    "Châtenay-Malabry",
    "Palaiseau",
    "Istres",
    "Villefranche-sur-Saône",
    "Saint-Martin",
    "Saint-Leu",
    "Saint-Cloud",
    "Cachan",
    "Le Perreux-sur-Marne",
    "Houilles",
    "Villeneuve-Saint-Georges",
    "Montigny-le-Bretonneux",
    "Franconville",
    "Conflans-Sainte-Honorine",
    "Saint-Raphaël",
    "Plaisir",
    "Sainte-Marie",
    "Villeneuve-la-Garenne",
    "La Ciotat",
    "Le Chesnay-Rocquencourt",
    "Sannois",
    "Saint-Genis-Laval",
    "Saint-Égrève",
    "Saint-Médard-en-Jalles",
    "Saint-Sébastien-sur-Loire",
    "Saint-Laurent-du-Var",
    "Draveil",
    "Saint-Étienne-du-Rouvray",
    "Sotteville-lès-Rouen",
    "Le Plessis-Robinson",
    "Bois-Colombes",
    "Le Plessis-Trévise",
    "Saint-Michel-sur-Orge",
    "Saint-Jean-de-Braye",
    "Saint-Jean-de-Luz",
    "Saint-Jean-de-Maurienne",
    "Saint-Jean-de-Védas",
    "Saint-Jean-Pied-de-Port",
    "Saint-Jean-Pla-de-Corts",
    "Saint-Jean-Poutge",
    "Saint-Jean-Poutge",
    "Saint-Jean-Poutge",
    "Saint-Jean-Poutge",
    "Saint-Jean-Poutge",
  ],
  Italy: [
    "Rom",
    "Mailand",
    "Neapel",
    "Turin",
    "Palermo",
    "Genua",
    "Bologna",
    "Florenz",
    "Bari",
    "Catania",
    "Venedig",
    "Verona",
    "Messina",
    "Padua",
    "Triest",
    "Brescia",
    "Prato",
    "Tarent",
    "Modena",
    "Reggio Calabria",
    "Reggio nell'Emilia",
    "Perugia",
    "Livorno",
    "Ravenna",
    "Cagliari",
    "Foggia",
    "Rimini",
    "Salerno",
    "Ferrara",
    "Sassari",
    "Latina",
    "Giugliano in Campania",
    "Monza",
    "Siracusa",
    "Pescara",
    "Bergamo",
    "Forlì",
    "Trient",
    "Vicenza",
    "Terni",
    "Novara",
    "Piacenza",
    "Ancona",
    "Andria",
    "Arezzo",
    "Udine",
    "Cesena",
    "Lecce",
    "La Spezia",
    "Pesaro",
    "Alessandria",
    "Pisa",
    "Catanzaro",
    "Pistoia",
    "Brindisi",
    "Como",
    "Treviso",
    "Busto Arsizio",
    "Marsala",
    "Gela",
    "Pavia",
    "Castellammare di Stabia",
    "Carrara",
    "Sesto San Giovanni",
    "Varese",
    "Fiumicino",
    "Cinisello Balsamo",
    "Matera",
    "Crotone",
    "Pordenone",
    "Agrigent",
    "Massa",
    "Trapani",
    "Altamura",
    "Imola",
    "L'Aquila",
    "Viterbo",
    "Cosenza",
    "Avellino",
    "Ragusa",
    "Casoria",
    "Caserta",
    "Grosseto",
    "Barletta",
    "Guidonia Montecelio",
    "Lucca",
    "Marano di Napoli",
    "Afragola",
    "Lamezia Terme",
    "Legnano",
    "Cinisello Balsamo",
    "Pozzuoli",
    "Carpi",
    "Caltanissetta",
    "Quartu Sant'Elena",
    "Battipaglia",
    "Sassuolo",
    "San Severo",
    "Benevento",
    "Cerignola",
    "Moncalieri",
    "Bisceglie",
    "Vigevano",
    "Cuneo",
    "Siena",
    "Aprilia",
    "Nichelino",
    "Fano",
    "Avellino",
    "Scafati",
    "Manfredonia",
    "Aversa",
    "San Giorgio a Cremano",
    "San Benedetto del Tronto",
    "Portici",
    "Montesilvano",
    "Vittoria",
    "Chieti",
    "Civitanova Marche",
    "Cava de' Tirreni",
    "Viareggio",
    "Crotone",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
    "Pavia",
    "Lodi",
    "Civitanova Marche",
    "Caltagirone",
    "Rovigo",
    "Asti",
    "Gallarate",
    "Cecina",
    "Pomezia",
    "Molfetta",
    "Rho",
  ],
  Spain: [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Sevilla",
    "Zaragoza",
    "Málaga",
    "Murcia",
    "Palma de Mallorca",
    "Las Palmas de Gran Canaria",
    "Bilbao",
    "Alicante",
    "Córdoba",
    "Valladolid",
    "Vigo",
    "Gijón",
    "L'Hospitalet de Llobregat",
    "A Coruña",
    "Vitoria-Gasteiz",
    "Granada",
    "Elche",
    "Oviedo",
    "Santa Cruz de Tenerife",
    "Badalona",
    "Cartagena",
    "Terrassa",
    "Jerez de la Frontera",
    "Sabadell",
    "Móstoles",
    "Alcalá de Henares",
    "Pamplona",
    "Fuenlabrada",
    "Almería",
    "Leganés",
    "San Sebastián",
    "Santander",
    "Burgos",
    "Castellón de la Plana",
    "Albacete",
    "Getafe",
    "Alcorcón",
    "Logroño",
    "Badajoz",
    "Salamanca",
    "Huelva",
    "Lleida",
    "Marbella",
    "Tarragona",
    "León",
    "Cádiz",
    "Jaén",
    "Ourense",
    "Lugo",
    "Santiago de Compostela",
    "Cáceres",
    "Melilla",
    "Ceuta",
    "Guadalajara",
    "Toledo",
    "Pontevedra",
    "Palencia",
    "Ferrol",
    "Girona",
    "San Fernando",
    "Roquetas de Mar",
    "Torrevieja",
    "Mataró",
    "Dos Hermanas",
    "Algeciras",
    "Santa Coloma de Gramenet",
    "Parla",
    "San Cristóbal de La Laguna",
    "Lorca",
    "Santiago de Compostela",
    "Torrejón de Ardoz",
    "Telde",
    "El Puerto de Santa María",
    "Alcalá de Guadaíra",
    "Pontevedra",
    "Coslada",
    "Orihuela",
    "Pozuelo de Alarcón",
    "Rivas-Vaciamadrid",
    "Rubí",
    "Manresa",
    "Fuengirola",
    "Mijas",
    "San Sebastián de los Reyes",
    "La Línea de la Concepción",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
    "Sagunto",
    "Ávila",
    "Cuenca",
    "Arrecife",
    "Elda",
    "Collado Villalba",
    "Benalmádena",
    "Majadahonda",
    "Paterna",
    "Santa Lucía de Tirajana",
    "Torrelavega",
    "Molina de Segura",
    "Gandía",
    "Sanlúcar de Barrameda",
    "Motril",
    "Estepona",
    "Torremolinos",
    "Benidorm",
    "Alcobendas",
    "Zamora",
  ],
  Germany: [
    "Berlin",
    "Kempten",
    "Hamburg",
    "München",
    "Köln",
    "Frankfurt am Main",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dortmund",
    "Essen",
    "Bremen",
    "Dresden",
    "Hannover",
    "Nürnberg",
    "Duisburg",
    "Bochum",
    "Wuppertal",
    "Bielefeld",
    "Bonn",
    "Münster",
    "Karlsruhe",
    "Mannheim",
    "Augsburg",
    "Wiesbaden",
    "Gelsenkirchen",
    "Mönchengladbach",
    "Braunschweig",
    "Chemnitz",
    "Kiel",
    "Aachen",
    "Halle (Saale)",
    "Magdeburg",
    "Freiburg im Breisgau",
    "Krefeld",
    "Lübeck",
    "Oberhausen",
    "Erfurt",
    "Mainz",
    "Rostock",
    "Kassel",
    "Hagen",
    "Saarbrücken",
    "Hamm",
    "Potsdam",
    "Ludwigshafen am Rhein",
    "Mülheim an der Ruhr",
    "Oldenburg",
    "Osnabrück",
    "Leverkusen",
    "Heidelberg",
    "Darmstadt",
    "Solingen",
    "Herne",
    "Neuss",
    "Regensburg",
    "Paderborn",
    "Ingolstadt",
    "Offenbach am Main",
    "Würzburg",
    "Fürth",
    "Ulm",
    "Heilbronn",
    "Pforzheim",
    "Wolfsburg",
    "Göttingen",
    "Bottrop",
    "Recklinghausen",
    "Reutlingen",
    "Bremerhaven",
    "Koblenz",
    "Bergisch Gladbach",
    "Jena",
    "Remscheid",
    "Erlangen",
    "Trier",
    "Salzgitter",
    "Moers",
    "Siegen",
    "Hildesheim",
    "Cottbus",
    "Gera",
    "Kaiserslautern",
    "Schwerin",
    "Witten",
    "Zwickau",
    "Gütersloh",
    "Iserlohn",
    "Hanau",
    "Esslingen am Neckar",
    "Ludwigsburg",
    "Düren",
    "Tübingen",
    "Flensburg",
    "Villingen-Schwenningen",
    "Gießen",
    "Ratingen",
    "Lünen",
    "Dessau-Roßlau",
    "Marl",
    "Velbert",
    "Lüdenscheid",
    "Wilhelmshaven",
    "Konstanz",
    "Norderstedt",
    "Neumünster",
    "Delmenhorst",
    "Gladbeck",
    "Rheine",
    "Troisdorf",
    "Dorsten",
    "Detmold",
    "Castrop-Rauxel",
    "Langenfeld (Rheinland)",
    "Arnsberg",
    "Bamberg",
    "Bayreuth",
    "Bocholt",
    "Celle",
    "Dinslaken",
    "Lingen (Ems)",
    "Neuwied",
    "Nürtingen",
    "Sankt Augustin",
    "Stolberg (Rheinland)",
    "Weimar",
    "Wetzlar",
    "Worms",
    "Zweibrücken",
  ],
  Japan: ["Tokyo", "Kyoto"],
  Thailand: [
    "Bangkok",
    "Chiang Mai",
    "Nakhon Ratchasima",
    "Khon Kaen",
    "Hat Yai",
    "Udon Thani",
    "Chon Buri",
    "Pattaya",
    "Nonthaburi",
    "Pak Kret",
    "Phitsanulok",
    "Nakhon Si Thammarat",
    "Surat Thani",
    "Pattaya", // Berühmt-berüchtigte Walking Street
    "Phuket", // Patong Beach mit Bangla Road
    "Koh Phangan", // Full Moon Party, Half Moon, Jungle Experience
    "Koh Samui", // Green Mango Club, Ark Bar
    "Krabi (Ao Nang)", // Chillige Strandpartys & Bars
    "Koh Tao", // Kleine Bars und Full Moon Vibes im Mini-Format
    "Pai", // Alternative Szene, Live-Musik, entspannte Vibes
    "Koh Phi Phi", // Feiern am Strand – Slinky, Ibiza Pool Party, Apache Bar
    "Hua Hin", // Weniger wild, aber viele Rooftop Bars und Clubs
    "Hat Yai", // Grenznahe Großstadt mit aktiver Nachtkultur
    "Ubon Ratchathani",
    "Nakhon Pathom",
    "Rayong",
    "Lampang",
    "Samut Prakan",
    "Mueang Nonthaburi",
    "Si Racha",
    "Phra Pradaeng",
    "Khlong Luang",
    "Nakhon Sawan",
    "Ratchaburi",
    "Songkhla",
    "Sakon Nakhon",
    "Yala",
    "Samut Sakhon",
    "Trang",
    "Saraburi",
    "Mae Sot",
    "Chiang Rai",
    "Kamphaeng Phet",
    "Phuket",
    "Chanthaburi",
    "Nong Khai",
    "Phetchabun",
    "Phetchaburi",
    "Chachoengsao",
    "Chumphon",
    "Kalasin",
    "Lopburi",
    "Nakhon Phanom",
    "Narathiwat",
    "Roi Et",
    "Suphan Buri",
    "Tak",
    "Uttaradit",
    "Yasothon",
    "Phayao",
    "Prachuap Khiri Khan",
    "Pattani",
    "Nong Bua Lamphu",
    "Amnat Charoen",
    "Bueng Kan",
    "Sa Kaeo",
    "Samut Songkhram",
    "Satun",
    "Si Sa Ket",
    "Sing Buri",
    "Sukhothai",
    "Surin",
    "Trat",
    "Uthai Thani",
    "Phichit",
    "Phrae",
    "Nan",
    "Mukdahan",
    "Loei",
    "Lamphun",
    "Chaiyaphum",
    "Chai Nat",
    "Chumphon",
    "Buriram",
    "Ang Thong",
    "Prachin Buri",
    "Phang Nga",
    "Phatthalung",
    "Nakhon Nayok",
    "Krabi",
    "Khon Kaen",
    "Kanchanaburi",
    "Chon Buri",
    "Chachoengsao",
    "Ayutthaya",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
    "Bang Bon",
    "Bang Bua Thong",
    "Bang Kruai",
    "Bang Lamung",
    "Bang Phli",
    "Bang Sao Thong",
    "Bang Sue",
    "Bangkok Port",
    "Bangkok Noi",
    "Bangkok Yai",
    "Bang Khen",
    "Bang Kapi",
  ],
  Mexico: ["Mexico City", "Tulum"],
  Brazil: ["Rio de Janeiro", "São Paulo"],
  Australia: ["Sydney", "Melbourne"],
  Canada: ["Vancouver", "Montreal"],
  India: ["Delhi", "Goa"],
  Greece: ["Athens", "Santorini"],
  Turkey: ["Istanbul", "Cappadocia"],
  Morocco: ["Marrakech", "Chefchaouen"],
  Vietnam: ["Hanoi", "Hoi An"],
  Portugal: ["Lisbon", "Porto"],
  Switzerland: ["Zürich", "Genf"],
  Netherlands: [
    "Amsterdam", // ca. 936.674 Einwohner
    "Rotterdam", // ca. 670.610 Einwohner
    "Den Haag", // ca. 566.221 Einwohner
    "Utrecht", // ca. 374.238 Einwohner
    "Eindhoven", // ca. 234.235 Einwohner
    "Tilburg", // ca. 219.632 Einwohner
    "Groningen", // ca. 203.105 Einwohner
    "Almere", // ca. 211.514 Einwohner
    "Breda", // ca. 184.403 Einwohner
    "Nijmegen", // ca. 177.818 Einwohner
    "Enschede", // ca. 158.542 Einwohner
    "Haarlem", // ca. 161.265 Einwohner
    "s-Hertogenbosch", // ca. 160.783 Einwohner
  ],
  Belgium: ["Brussels", "Antwerp"],
  Austria: ["Vienna", "Salzburg"],
  Poland: ["Warsaw", "Cracow"],
  Hungary: ["Budapest", "Debrecen"],
};
